stages:
  - test
  - release

before_script:
  - npm install

node:8:
  image: node:8
  stage: test
  script:
    - npm run build

node:10:
  image: node:10
  stage: test
  script:
    - npm run build

publish:
  image: node:10
  stage: release
  script:
    - npx semantic-release
