image: node:8

stages:
  - build
  - test
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script: npm test
  dependencies:
    - build

publish:
  stage: publish
  only:
    - master
  script:
    - npm run build:release
    - npx semantic-release
  dependencies:
    - test
