image: node:10

stages:
  - build
  - test
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn --frozen-lockfile --non-interactive
    - yarn build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script: yarn test:generate
  dependencies:
    - build
  artifacts:
    paths:
      - dist/
      - .jest-test-results.json

publish:
  stage: publish
  only:
    - master
  script:
    - yarn build:release
    - yarn semantic-release
  dependencies:
    - build
    - test
