name: Publish Docs

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-docs:
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: | # uses partial matches
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Remove Vue devtools header
        run: rm config/storybook/preview-head.html
      - name: Build docs
        run: yarn build:storybook
      - name: Deploy docs
        run: npx netlify deploy -a $NETLIFY_AUTH_TOKEN -d storybook-static/ -p -m "${{ github.repository }}@${{ github.ref }}"
