name: Release

on:
  push:
    branches:
      - alpha
      - master

jobs:
  install:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v2
      - name: Install
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: | # uses partial matches
            ${{ runner.os }}-yarn-
      - name: Cache workspace
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: schedio-${{ github.sha }}
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    needs: install
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Restore workspace
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: schedio-${{ github.sha }}
      - run: yarn test:generate
      - run: yarn build:release
      - run: yarn semantic-release
